name: CD-Release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  create-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install -y build-essential zip gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine64
      - name: Install go dependencies
        run: |
          go get github.com/sirupsen/logrus
          go get github.com/ipfs/go-ipfs-api
          go get github.com/mjibson/esc
      - name: Build libipfs for windows & linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: make build_linux && make build_windows
      - name: Build libipfs for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: make build_macos
      - name: Pacakge artifacts linux and windows
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir libipfs-${{ github.ref }}-win-x64/
          cp -rf ./bin/libipfs-windows* libipfs-${{ github.ref }}-win-x64/
          zip -r libipfs-${{ github.ref }}-win-x64.zip libipfs-${{ github.ref }}-win-x64/
          mkdir libipfs-${{ github.ref }}-linux-x64/
          cp -rf ./bin/libipfs-linux* libipfs-${{ github.ref }}-linux-x64/
          zip -r libipfs-${{ github.ref }}-linux-x64.zip libipfs-${{ github.ref }}-linux-x64/
      - name: Pacakge artifacts macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          mkdir libipfs-${{ github.ref }}-macOS-x64/
          cp -rf ./bin/* libipfs-${{ github.ref }}-macOS-x64/
          zip -r libipfs-${{ github.ref }}-macOS-x64.zip libipfs-${{ github.ref }}-macOS-x64/
      - name: Upload aritifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./libipfs-${{ github.ref }}-all-platforms-x64.zip
          asset_name: libipfs-${{ github.ref }}-all-platforms-x64.zip
          asset_content_type: application/zip