name: Release
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: libipfs Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
        
  build-and-publish:
    name: Publish release
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install dependencies for macOS build
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          go mod download
      - name: Build and package artifacts for macOS build
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make build_macos_x64
          mkdir libipfs${{ github.event.release.tag_name }}-macOS-x64/
          cp -rf ./bin/libipfs-mac* libipfs${{ github.event.release.tag_name }}-macOS-x64/
          zip -r libipfs${{ github.event.release.tag_name }}-macOS-x64.zip libipfs${{ github.event.release.tag_name }}-macOS-x64/
      - name: Upload macOS build artifacts
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./libipfs${{ github.event.release.tag_name }}-macOS-x64.zip
          asset_name: libipfs${{ github.event.release.tag_name }}-macOS-x64.zip
          asset_content_type: application/zip