name: CD-Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: libipfs-${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install -y build-essential zip gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine64
      - name: Install go dependencies
        run: |
          go get github.com/sirupsen/logrus
          go get github.com/ipfs/go-ipfs-api
          go get github.com/mjibson/esc
      - name: Build libipfs for windows & linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: make build_linux && make build_windows
      - name: Build libipfs for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: make build_macos
      - name: Pacakge artifacts
        run: |
          mkdir libipfs-${{ github.ref }}-all-platforms/
          cp -rf ./bin/* libipfs-${{ github.ref }}-all-platforms/
          zip -r libipfs-${{ github.ref }}-all-platforms.zip libipfs-${{ github.ref }}-all-platforms/
      - name: Upload aritifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./libipfs-${{ github.ref }}-all-platforms-x64.zip
          asset_name: libipfs-${{ github.ref }}-all-platforms-x64.zip
          asset_content_type: application/zip