name: Build Test
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install linux dependencies
      run: sudo apt update && sudo apt install -y build-essential
    - name: Install go dependencies
      run: |
        go get github.com/sirupsen/logrus
        go get github.com/ipfs/go-ipfs-api
        go get github.com/mjibson/esc
    - name: Build libipfs
      run: make build_linux

  build-windows:
    runs-on: windows-latest
    env:
      CCACHE_COMPRESS: 1
      CCACHE_TEMPDIR: C:\Users\runneradmin\.ccache-temp
      CCACHE_DIR: C:\Users\runneradmin\.ccache
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.ccache
        key: ccache-windows-build-${{ github.sha }}
        restore-keys: ccache-windows-build-
    - uses: eine/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-go mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git
    - name: Set GOROOT and GOPATH
      run: |
        export GOROOT=/mingw64/lib/go
        export GOPATH=/mingw64
    - name: Install go dependencies
      run: |
        go get github.com/sirupsen/logrus
        go get github.com/ipfs/go-ipfs-api
        go get github.com/mjibson/esc
    - name: Build libipfs
      run: make build_windows

  build-macos:
    runs-on: macOS-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install go dependencies
      run: |
        go get github.com/sirupsen/logrus
        go get github.com/ipfs/go-ipfs-api
        go get github.com/mjibson/esc
    - name: Build libipfs
      run: make build_macos