name: CD-Release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

  build-and-publish:
    name: Publish release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install -y build-essential zip gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine64
      - name: Install go dependencies
        run: |
          go get github.com/sirupsen/logrus
          go get github.com/ipfs/go-ipfs-api
          go get github.com/mjibson/esc
      - name: Build libipfs for windows & linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: make build_linux
      - name: Build libipfs for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: make build_macos

      - name: Pacakge artifacts linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir libipfs-${{ github.event.release.tag_name }}-linux-x64/
          cp -rf ./bin/libipfs-linux* libipfs-${{ github.event.release.tag_name }}-linux-x64/
          zip -r libipfs-${{ github.event.release.tag_name }}-linux-x64.zip libipfs-${{ github.event.release.tag_name }}-linux-x64/

      - name: Pacakge artifacts macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          mkdir libipfs-${{ github.event.release.tag_name }}-macOS-x64/
          cp -rf ./bin/* libipfs-${{ github.event.release.tag_name }}-macOS-x64/
          zip -r libipfs-${{ github.event.release.tag_name }}-macOS-x64.zip libipfs-${{ github.event.release.tag_name }}-macOS-x64/

      - name: Upload aritifacts for linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./libipfs-${{ github.event.release.tag_name }}-linux-x64.zip
          asset_name: libipfs-${{ github.event.release.tag_name }}-linux-x64.zip
          asset_content_type: application/zip
          
      - name: Upload aritifacts for macOS
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./libipfs-${{ github.event.release.tag_name }}-macOS-x64.zip
          asset_name: libipfs-${{ github.event.release.tag_name }}-macOS-x64.zip
          asset_content_type: application/zip