name: Build
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install linux build dependencies
      run: sudo apt update && sudo apt install -y build-essential
    - name: Install go dependencies
      run: |
        go mod download
    - name: Build libipfs
      run: make build_linux

  build-windows:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install windows build dependencies
      run: sudo apt update && sudo apt install -y build-essential gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine64
    - name: Install go dependencies
      run: |
        go mod download
    - name: Build libipfs
      run: make build_windows

  build-macos-x64:
    runs-on: macOS-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install go dependencies
      run: |
        go mod download
    - name: Build libipfs
      run: make build_macos_x64
