name: FyneApp Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Download dependencies
      run: go mod download

    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Run make build
      run: make build

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fyne-app-artifacts
        path: ./dist  # or the directory where the compiled binaries are located
